name: ci
on:
  push:
    branches: [main]
  pull_request:

env:
  DAGGER_VERSION: "0.10.3"

jobs:
  build:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build binaries
        uses: dagger/dagger-for-github@v5
        with:
          version: $DAGGER_VERSION
          verb: call
          module: github.com/${{ github.repository }}@${{ github.ref }}
          args: build-all --dir . --platforms "linux/amd64,linux/arm64" -o bin

      - uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: ./bin

      - name: Build image (linux/amd64)
        uses: dagger/dagger-for-github@v5
        with:
          version: $DAGGER_VERSION
          verb: call
          module: github.com/${{ github.repository }}@${{ github.ref }}
          args: build-image --dir . --platform "linux/amd64" stdout

      - name: Build image (linux/arm64)
        uses: dagger/dagger-for-github@v5
        with:
          version: $DAGGER_VERSION
          verb: call
          module: github.com/${{ github.repository }}@${{ github.ref }}
          args: build-image --dir . --platform "linux/arm64"
