name: ci
on:
  push:
    branches: [main]
  pull_request:

env:
  DAGGER_VERSION: "0.10.3"
  # _EXPERIMENTAL_DAGGER_RUNNER_HOST: ${{ secrets._EXPERIMENTAL_DAGGER_RUNNER_HOST }}
  DOCKER_SCOUT_HUB_USER: ${{ vars.DOCKER_SCOUT_HUB_USER }}
  DOCKER_SCOUT_HUB_PASSWORD: ${{ secrets.DOCKER_SCOUT_HUB_PASSWORD }}

jobs:
  build:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Go build
        uses: dagger/dagger-for-github@v5
        with:
          version: $DAGGER_VERSION
          verb: call
          module: github.com/felipecruz91/daggerverse/go@7e62a72c84a5e19c58637ee50a22a36dd096f555
          args: build --source . --platforms "linux/amd64,linux/arm64" -o bin
          engine-stop: false

      - name: Go tests
        uses: dagger/dagger-for-github@v5
        with:
          version: $DAGGER_VERSION
          verb: call
          module: github.com/felipecruz91/daggerverse/go@7e62a72c84a5e19c58637ee50a22a36dd096f555
          args: test --source . --verbose=true
          engine-stop: false

      - name: Build Docker image (linux/amd64)
        uses: dagger/dagger-for-github@v5
        with:
          version: $DAGGER_VERSION
          verb: call
          module: github.com/felipecruz91/daggerverse/go@7e62a72c84a5e19c58637ee50a22a36dd096f555
          args: docker-build --bin bin --platform "linux/amd64" export --path image-linux-amd64.tar
          engine-stop: false

      - name: Build image (linux/arm64)
        uses: dagger/dagger-for-github@v5
        with:
          version: $DAGGER_VERSION
          verb: call
          module: github.com/felipecruz91/daggerverse/go@7e62a72c84a5e19c58637ee50a22a36dd096f555
          args: docker-build --bin bin --platform "linux/arm64" export --path image-linux-arm64.tar
          engine-stop: true
